version: '3'
services:
  frontend:
    depends_on:
        - backend
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    
  backend:
    depends_on:
      - postgres
    build:
      context: ./backend
    volumes:
      - ./backend:/app
    ports:
      - "4000:4000"
    environment:
      - MIX_ENV=dev
      - DATABASE_URL=postgres://postgres:postgres@postgres/backend_dev

  postgres:
    image: postgres:10
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=backend_dev
    ports:
      - 5432:5432